base_url = "https://ming-blog.netlify.app/"
build_search_index = false
compile_sass = false
default_language = "zh-TW"
description = "ming 的部落格，主要會有程式語言、生活紀錄等內容"
generate_feed = true
generate_rss = true
taxonomies = [
  {name = "tags", feed = true},
  {name = "categories", feed = true},
  {name = "kinds", feed = true},
]
title = "Ming's Blog"

[markdown]
# When set to "true", all code blocks are highlighted.
highlight_code = true
# highlight_theme = "Tomorrow"
# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether to set rel="nofollow" for all external links
external_links_no_follow = false

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = false

smart_punctuation = false

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = true
# Whether to include the path of the page/section in the index
include_path = true
# Whether to include the rendered content of the page/section in the index
include_content = false

[extra]
author = "ming"
email = "ja99181@gmail.com"
theme_color = "#003c6d"

### THIRD PARTY
google_analytics = ""

### I18N WORDS

[slugify]
paths = "on"
taxonomies = "on"

[translations]
keywords = "ROS, 程式語言"
label_all_posts = "[看所有文章 ➞](/blog/)"
label_all_impression = "[看所有 Impression ➞](/impression/)"
label_all_thoughts = "[看所有 Thoughts ➞](/thoughts/)"
label_archive = "Blog 歸檔"
label_impression_archive = "Impression 歸檔"
label_thoughts_archive = "Thoughts 歸檔"
label_back_to_start = "本文開始"
label_categories = "所有分類"
label_kinds = "所有類別"
label_impression = "Impression: "
label_category = "Category: "
label_created = "Posted"
label_home = "首頁"
label_new_posts_list_title = "最新 Blog 文章"
label_new_thoughts_list_title = "最新 Thoughts"
label_new_impression_list_title = "最新 Impression"
label_read_more = "繼續閱讀全文 ➞"
label_rss = "訂閱RSS"
label_table_contents = "目錄"
label_sorting_articles ="看更多"
label_tag = "Tags: "
label_tags = "依標籤"
label_timeline = "依時序"
label_taxonomy = "類別"
label_updated = "Last Modified"
label_mail = "ja99181@gmail.com"
label_icon = "https://dotown.maeda-design-room.net/wp-content/uploads/2022/01/thing_cats_06.png"